In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3]])
print(array.ndim)

2


In [3]:
array.ndim

2

In [4]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [5]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [6]:
array_float1 = np.array([1.1, 2.3,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [7]:
zero_array =np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [8]:
array1 = np.arange(8)
array3d= array1.reshape((2,2,2))
print(array3d.tolist())

array5 = array3d.reshape(-1, 1)
print(array5.tolist())
print(array5.shape)

array6 = array3d.reshape(1, -1)
print(array6.tolist())
print(array6.shape)


[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
[[0, 1, 2, 3, 4, 5, 6, 7]]
(1, 8)


In [9]:
array1 = np.arange(start=1, stop=10)
print(array1)
value = array1[2]
print(value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>


In [10]:
array1d= np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print(array3.tolist())

array4 = array2d[[0,1], 0:2]
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5.tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [11]:
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [12]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [13]:
boolean_indexes=  np.array([False, False, False, False, False,  True,  True,  True,  True])
array3= array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [14]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


In [15]:
org_array = np.array([3, 1, 9, 5])
print(org_array)
sort_array1 = np.sort(org_array)
print(sort_array1)


[3 1 9 5]
[1 3 5 9]


In [16]:
print(org_array)
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

[3 1 9 5]
None
[1 3 5 9]


In [17]:
sort_array_desc = np.sort(org_array)[::-1]
print(sort_array_desc)

[9 5 3 1]


In [20]:
array2d = np.array([[8,12],
                   [7, 1]])

sort_array2d_axis = np.sort(array2d , axis = 0)
print(sort_array2d_axis)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [21]:
ort_array = np.array([3,1,9,5])
sort_indicies = np.argsort(org_array)
print(type(sort_indicies))
print(sort_indicies)

<class 'numpy.ndarray'>
[0 1 2 3]


In [23]:
org_array = np.array([3,1, 9, 5])
sort_indiceis_desc = np.argsort(org_array)[::-1]
print(sort_indiceis_desc)

[2 3 0 1]


In [24]:
name_array = np.array(['John', 'Mike', 'Sara', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98,88])

sort_indiceis_asc = np.argsort(score_array)
print(sort_indiceis_asc)
print(name_array[sort_indiceis_asc])

[0 2 4 1 3]
['John' 'Sara' 'Samuel' 'Mike' 'Kate']


In [25]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [26]:
A = np.array([[1,2],
              [3,4]])
transpose_mat= np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
